from PyQt5 import QtCore, QtGui, QtWidgets


class Example(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setEnabled(True)
        self.statusbar.setToolTip("")
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuMenuSub = QtWidgets.QMenu(self.menuMenu)
        self.menuMenuSub.setObjectName("menuMenuSub")
        self.menuMenuDelayed = QtWidgets.QMenu(self.menubar)
        self.menuMenuDelayed.setObjectName("menuMenuDelayed")
        self.menuMenu_Disabled = QtWidgets.QMenu(self.menubar)
        self.menuMenu_Disabled.setEnabled(False)
        self.menuMenu_Disabled.setObjectName("menuMenu_Disabled")
        self.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(self)
        self.toolBar.setObjectName("toolBar")
        self.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionA = QtWidgets.QAction(self)
        self.actionA.setIconVisibleInMenu(True)
        self.actionA.setObjectName("actionA")
        self.action1 = QtWidgets.QAction(self)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(self)
        self.action2.setObjectName("action2")
        self.actionActionDelayedA = QtWidgets.QAction(self)
        self.actionActionDelayedA.setObjectName("actionActionDelayedA")
        self.actionActionDelayedSubA = QtWidgets.QAction(self)
        self.actionActionDelayedSubA.setEnabled(True)
        self.actionActionDelayedSubA.setObjectName("actionActionDelayedSubA")
        self.actionActionCheckableA = QtWidgets.QAction(self)
        self.actionActionCheckableA.setCheckable(True)
        self.actionActionCheckableA.setObjectName("actionActionCheckableA")
        self.actionActionCheckableSubAChecked = QtWidgets.QAction(self)
        self.actionActionCheckableSubAChecked.setCheckable(True)
        self.actionActionCheckableSubAChecked.setChecked(True)
        self.actionActionCheckableSubAChecked.setObjectName("actionActionCheckableSubAChecked")
        self.actionActionCheckableSubAUnchecked = QtWidgets.QAction(self)
        self.actionActionCheckableSubAUnchecked.setCheckable(True)
        self.actionActionCheckableSubAUnchecked.setObjectName("actionActionCheckableSubAUnchecked")
        self.actionNewB = QtWidgets.QAction(self)
        self.actionNewB.setObjectName("actionNewB")
        self.actionNewC = QtWidgets.QAction(self)
        self.actionNewC.setObjectName("actionNewC")
        self.actionNewD = QtWidgets.QAction(self)
        self.actionNewD.setObjectName("actionNewD")
        self.actionNewE = QtWidgets.QAction(self)
        self.actionNewE.setObjectName("actionNewE")
        self.actionB = QtWidgets.QAction(self)
        self.actionB.setObjectName("actionB")
        self.actionC = QtWidgets.QAction(self)
        self.actionC.setObjectName("actionC")
        self.actionD = QtWidgets.QAction(self)
        self.actionD.setEnabled(False)
        self.actionD.setObjectName("actionD")
        self.actionAction_Disabled = QtWidgets.QAction(self)
        self.actionAction_Disabled.setEnabled(False)
        self.actionAction_Disabled.setObjectName("actionAction_Disabled")
        self.action3 = QtWidgets.QAction(self)
        self.action3.setObjectName("action3")
        self.actionE = QtWidgets.QAction(self)
        self.actionE.setCheckable(False)
        self.actionE.setIconVisibleInMenu(True)
        self.actionE.setObjectName("actionE")
        self.actionF = QtWidgets.QAction(self)
        self.actionF.setCheckable(True)
        self.actionF.setChecked(True)
        self.actionF.setObjectName("actionF")
        self.actionAction_G = QtWidgets.QAction(self)
        self.actionAction_G.setObjectName("actionAction_G")
        self.menuMenuSub.addAction(self.action1)
        self.menuMenuSub.addAction(self.action2)
        self.menuMenuSub.addAction(self.action3)
        self.menuMenu.addAction(self.actionA)
        self.menuMenu.addAction(self.actionB)
        self.menuMenu.addAction(self.actionC)
        self.menuMenu.addAction(self.menuMenuSub.menuAction())
        self.menuMenu.addAction(self.actionD)
        self.menuMenu.addAction(self.actionE)
        self.menuMenu.addAction(self.actionF)
        self.menuMenuDelayed.addAction(self.actionActionDelayedA)
        self.menuMenu_Disabled.addAction(self.actionAction_Disabled)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuMenuDelayed.menuAction())
        self.menubar.addAction(self.menuMenu_Disabled.menuAction())
        self.toolBar.addAction(self.actionA)
        self.toolBar.addAction(self.actionB)
        self.toolBar.addAction(self.actionC)
        self.toolBar.addAction(self.actionE)




        self.menuMenu.setTitle("Menu")
        self.menuMenuSub.setTitle("Submenu")
        self.menuMenuDelayed.setTitle("Delayed Menu")
        self.menuMenu_Disabled.setTitle("Disabled Menu")
        self.toolBar.setWindowTitle("toolBar")
        self.actionA.setText("Action A")
        self.action1.setText("Submenu Action 1")
        self.action1.setToolTip("Action A Sub")
        self.action2.setText("Submenu Action 2")
        self.actionActionDelayedA.setText("Delayed Menu Action")
        self.actionActionDelayedA.setToolTip("Action Delayed A")
        self.actionActionDelayedSubA.setText("Action Delayed Sub A")
        self.actionActionDelayedSubA.setToolTip("Action Delayed Sub A")
        self.actionActionCheckableA.setText("Action Checkable A")
        self.actionActionCheckableA.setToolTip("Action Checkable A")
        self.actionActionCheckableSubAChecked.setText("Action Checkable Sub A Checked")
        self.actionActionCheckableSubAChecked.setToolTip("Action Checkable Sub A Checked")
        self.actionActionCheckableSubAUnchecked.setText("Action Checkable Sub A Unchecked")
        self.actionActionCheckableSubAUnchecked.setToolTip("Action Checkable Sub A Unchecked")
        self.actionNewB.setText("New B")
        self.actionNewC.setText("New C")
        self.actionNewD.setText("New D")
        self.actionNewE.setText("New E")
        self.actionB.setText("Action B")
        self.actionC.setText("Action C")
        self.actionD.setText("Action D (Disabled)")
        self.actionAction_Disabled.setText("Action Menu Disabled")
        self.action3.setText("Submenu Action 3")
        self.actionE.setText("Action E (Checkable)")
        self.actionF.setText("Action F (Checkable)")
        self.actionAction_G.setText("Action G")


if __name__ == "__main__":
    app = QtWidgets.QApplication([])
    example = Example()
    example.show()
    app.exec_()
